pyannote/pyannote-audio

pyannote/audio/embedding/base.py
pyannote/audio/embedding/extraction.py
pyannote/audio/embedding/models.py
pyannote/audio/embedding/segmentation.py
pyannote/audio/embedding/triplet_loss/generator.py
pyannote/audio/generators/labels.py
pyannote/audio/generators/speech.py
pyannote/audio/generators/yaafe.py
pyannote/audio/keras_utils.py
pyannote/audio/labeling/aggregation.py
pyannote/audio/labeling/base.py
pyannote/audio/segmentation.py
scripts/speaker_embedding.py
scripts/speech_activity_detection.py
setup.py

* BREAKING: remove support for sequence normalization
* BREAKING: remove support for TristouNet "last" pooling
* BREAKING: remove "output_dim" parameter (is now included in new "mlp" parameter)
* BREAKING: rename "dense" to "mlp"
* BREAKING: rename "LabeledFixedDurationSequencesBatchGenerator" to "FixedDurationSequences"

feat: add support for embedding of sequences with variable length

---

pyannote/audio/embedding/__init__.py
pyannote/audio/embedding/base.py
pyannote/audio/embedding/extraction.py
pyannote/audio/embedding/glue.py
pyannote/audio/embedding/segmentation.py
pyannote/audio/embedding/triplet_loss/generator.py
pyannote/audio/embedding/triplet_loss/glue.py
pyannote/audio/generators/labels.py
pyannote/audio/generators/speech.py
pyannote/audio/generators/yaafe.py
pyannote/audio/labeling/aggregation.py
pyannote/audio/segmentation.py
scripts/speaker_embedding.py
scripts/speech_activity_detection.py
setup.py

* BREAKING: replace `get_shape` method by `shape` property
* improve: default `build_model` to return the embedding itself
* setup: update to pyannote.database 0.4.1

chore: major Glue and SequenceEmbedding.fit refactoring

---

pyannote/audio/features/with_yaafe.py

add a new configuration in Yaafe extractor: concatenate adjacent MFCCs

concatenation of adjacent MFCCs in Yaafe

---

pyannote/audio/embedding/approaches/center_loss.py
pyannote/audio/embedding/approaches/triplet_loss.py

feat: add triplet sampling strategies

---

pyannote/audio/applications/base.py
pyannote/audio/applications/change_detection.py
pyannote/audio/applications/speaker_embedding.py
pyannote/audio/features/utils.py
pyannote/audio/generators/periodic.py
pyannote/audio/labeling/aggregation.py
pyannote/audio/signal.py
setup.py

* BREAKING: add "percentile" parameter to Peak detection (set to True to get old behavior)
* BREAKING: use "audio" in place of (now unsupported) "wav" protocol key 
* feat: add Peak.tune method (to maximize coverage @ given purity)
* setup: switch to pyannote.metrics 1.2
* setup: switch to pyannote.generators 1.0

chore: refactor speaker change detection CLI

---

pyannote/audio/applications/feature_extraction.py

feat: add parallel processing to pyannote-speech-features

---

pyannote/audio/applications/base.py
pyannote/audio/train/trainer.py
requirements.txt

This PR fixes issue #181 
I tested this change with `pip install git+https://github.com/Mymoza/pyannote-audio.git@logdir-tensorboardx` and I didn't encounter the error reported in issue #181 anymore. :)

Fixed SummaryWriter logdir parameter name changed

---

pyannote/audio/labeling/tasks/speech_activity_detection.py

This pull request only adds some comments.

Added Docstring for DomainAdversarialSpeechActivityDetection

---

pyannote/audio/applications/speaker_embedding.py

fix: fix params.yml format when validating speaker embedding

---

pyannote/audio/models/models.py
pyannote/audio/models/pooling.py

- New abstract class `TemporalPooling` with the possibility to instanciate a subclass given its code name (`sum`, `max`, `last`, `x-vector`)
- Temporal pooling modules:
- `SumPool`
- `MaxPool`
- `LastPool`
- `StatsPool`
- `pyannote.audio.models.PyanNet` now uses these new modules

Temporal Pooling Algorithms as Separate PyTorch Modules

---

pyannote/audio/preprocessors/speech_activity_detection.py

- Fixed `RemoveNonSpeech` bug when no speech regions are found

Bugfix: RemoveNonSpeech fails when no speech is found

---

pyannote/audio/embedding/approaches/arcface_loss.py
pyannote/audio/embedding/approaches/base.py
pyannote/audio/embedding/approaches/center_loss.py
pyannote/audio/embedding/approaches/classification.py
pyannote/audio/embedding/approaches/coco_loss.py
pyannote/audio/embedding/approaches/contrastive_loss.py
pyannote/audio/embedding/approaches/triplet_loss.py

* chore: rename EmbeddingApproach to RepresentationLearning
* feat: inherit from EmbeddingApproach.get_batch_generator
* feat: add per_turn option to all approaches (for aggregation learning)
* BREAKING: remove support for variable length sequences

wip: refactor pyannote.audio.embedding.approaches

---

pyannote/audio/pipeline/overlap_detection.py
pyannote/audio/pipeline/resegmentation.py
pyannote/audio/pipeline/speaker_change_detection.py
pyannote/audio/pipeline/speaker_diarization.py
pyannote/audio/pipeline/speech_activity_detection.py
pyannote/audio/pipeline/speech_turn_assignment.py
pyannote/audio/pipeline/speech_turn_clustering.py
pyannote/audio/pipeline/speech_turn_segmentation.py
pyannote/audio/utils/path.py
tutorials/pipelines/speech_activity_detection/README.md
tutorials/pipelines/speech_activity_detection/config.yml

- feat: add Pre____ed wrapper around Precomputed and Pretrained classes
- fix: fixes #294

feat: add support for using pretrained models on-the-fly in pipelines

---

pyannote/audio/embedding/approaches/center_loss.py

- **Fixed:** Center loss wasn't recreating classifier layer and center parameters when fine-tuning a different dataset than that of pretraining.
- **Fixed:** `CenterLoss` was using `nn.Linear` for the classification layer, but a `target` parameter was being passed to `forward`. Switched to pyannote's `classification.Linear`.

Fix Center loss bugs

---

pyannote/audio/labeling/tasks/base.py
pyannote/audio/labeling/tasks/domain_classification.py
pyannote/audio/labeling/tasks/overlap_detection.py
pyannote/audio/labeling/tasks/speaker_change_detection.py
pyannote/audio/labeling/tasks/speech_activity_detection.py

@PaulLerner, can you please check this solves your issue?

feat: improve support for corpora with large number of speakers

---

pyannote/audio/applications/base.py
pyannote/audio/applications/base_labeling.py
pyannote/audio/applications/config.py
pyannote/audio/applications/speaker_embedding.py
pyannote/audio/augmentation/noise.py
pyannote/audio/features/pretrained.py

@MarvinLvn, would you mind checking that this solves the problem (and does not create new ones when running "train", "validate", "apply", and "torch.hub.load" ?)

fix: fix handling of audio preprocessors

---

tutorials/pipelines/speaker_diarization/README.md
tutorials/pretrained/model/README.md
tutorials/pretrained/pipeline/README.md

Just a few correction regarding the tutorials. More might be to come.

Tutorials' README.md corrections

---

.github/workflows/cli.yml
pyannote/audio/labeling/tasks/speaker_change_detection.py
tests/cli/scd_mfcc.sh
tests/cli/scd_mfcc/config.yml

fix: fix #377 and add corresponding CLI tests

---

pyannote/audio/core/model.py
pyannote/audio/core/task.py
pyannote/audio/tasks/mixins.py
pyannote/audio/tasks/multi_task_segmentation/task.py
pyannote/audio/tasks/overlapped_speech_detection/task.py
pyannote/audio/tasks/speaker_change_detection/task.py
pyannote/audio/tasks/speaker_tracking/task.py
pyannote/audio/tasks/speaker_verification/task.py
pyannote/audio/tasks/voice_activity_detection/task.py

This will allow the use of learning rate schedulers such as ReduceLROnPlateau.
https://pytorch-lightning.readthedocs.io/en/latest/optimizers.html#learning-rate-scheduling
Also factorizes segmentation tasks codebase as there was lots of redundant code between them.

feat: add validation loop

---

pyannote/audio/core/task.py
requirements.txt

fix: fix support for "ddp" multi-gpu training

---

pyannote/audio/applications/speaker_embedding.py
pyannote/audio/pipeline/speech_turn_assignment.py

Relates to https://github.com/pyannote/pyannote-audio/issues/471
I got good results with this in one experiment, so seems good to me!

feat(cropping): avoid strict cropping, and preferentially center crop

---

pyannote/audio/core/inference.py

fix: fix Inference docstring

---

.github/workflows/test.yml
tests/test_run_notebooks.py

feat: Code Coverage

---

pyannote/audio/core/inference.py

feat: add support for Inference.crop with a list of chunks

---

pyannote/audio/core/model.py

feat: add support for private huggingface.co models

---

pyannote/audio/models/segmentation/PyanNet.py

cc @juanmc2005 
Default behavior is to create one multi-layer LSTM (see `(lstm)` line below).
```python
from pyannote.audio.models.segmentation import PyanNet
PyanNet(lstm={'num_layers': 2})
```
```
PyanNet(
(sincnet): SincNet(
(wav_norm1d): InstanceNorm1d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
(conv1d): ModuleList(
(0): Encoder(
(filterbank): ParamSincFB()
)
(1): Conv1d(80, 60, kernel_size=(5,), stride=(1,))
(2): Conv1d(60, 60, kernel_size=(5,), stride=(1,))
)
(pool1d): ModuleList(
(0): MaxPool1d(kernel_size=3, stride=3, padding=0, dilation=1, ceil_mode=False)
(1): MaxPool1d(kernel_size=3, stride=3, padding=0, dilation=1, ceil_mode=False)
(2): MaxPool1d(kernel_size=3, stride=3, padding=0, dilation=1, ceil_mode=False)
)
(norm1d): ModuleList(
(0): …
```

feat: allow splitting multi-layer LSTMs into a list of one-layer LSTMs

---

pyannote/audio/__init__.py
pyannote/audio/core/inference.py
pyannote/audio/core/pipeline.py
pyannote/audio/pipelines/overlapped_speech_detection.py
pyannote/audio/pipelines/segmentation.py
pyannote/audio/pipelines/speaker_change_detection.py
pyannote/audio/pipelines/speaker_diarization.py
pyannote/audio/pipelines/speech_turn_assignment.py
pyannote/audio/pipelines/speech_turn_clustering.py
pyannote/audio/pipelines/speech_turn_segmentation.py
pyannote/audio/pipelines/voice_activity_detection.py

feat: add custom Pipeline subclass with from_pretrained class-method

---

pyannote/audio/core/model.py
pyannote/audio/core/pipeline.py

for compatibility with huggingface_hub>=0.0.2

huggingface_hub: drop the first param name

---

pyannote/audio/core/io.py

* fix(doc): fix "waveform" type in docstring

fix: fix corner case when seek-and-read fails

---

pyannote/audio/pipelines/overlapped_speech_detection.py
pyannote/audio/pipelines/segmentation.py
pyannote/audio/pipelines/voice_activity_detection.py
pyannote/audio/utils/signal.py

* BREAKING: drop support for "scale" parameter in Binarize
* BREAKING: drop support for "scale" parameter in Peak
* BREAKING: Binarize.__call__ now returns an instance of Annotation

feat: add support for multi-dimensional scores in Binarize

---

pyannote/audio/core/io.py

feat: add Audio.validate_file utility method

---

codecov.yml

Trying to stop the code cov patch check that is blocking PR's. 
Closes #587

chore: Remove code cov patch

---

pyannote/audio/core/model.py
pyannote/audio/core/pipeline.py

To address issue https://github.com/pyannote/pyannote-audio/issues/658

added cache_dir - https://github.com/pyannote/pyannote-audio/issues/658

---

pyannote/audio/tasks/segmentation/mixins.py
pyannote/audio/tasks/segmentation/segmentation.py

chore: make tensorboard logs lighter 

---

pyannote/audio/tasks/embedding/mixins.py

When training variable-duration speaker embedding (i.e. between `min_duration` and `duration`), only remove speech turns shorter than `min_duration` (instead of `duration`) and use zero-padding when that happens.

fix: fix embedding train dataloader

---

pyannote/audio/tasks/segmentation/segmentation.py

feat: add option to force maximum number of speakers

---

pyannote/audio/utils/preview.py

feat: add preview_training_samples utility

---

pyannote/audio/tasks/segmentation/segmentation.py
pyannote/audio/torchmetrics/__init__.py
pyannote/audio/torchmetrics/audio/__init__.py
pyannote/audio/torchmetrics/audio/diarization_error_rate.py
pyannote/audio/torchmetrics/functional/audio/diarization_error_rate.py

feat: add OptimalDiarizationErrorRate (torch)metric

---

pyannote/audio/core/model.py
pyannote/audio/core/pipeline.py
requirements.txt

setup: switch to latest hugginface_hub API

---

pyannote/audio/core/io.py

fix: rewind IOBase after reading

---

.pre-commit-config.yaml

Change to secure git protocol for pre-commit

---

pyannote/audio/tasks/segmentation/mixins.py
pyannote/audio/tasks/segmentation/segmentation.py

fix: fix corner case with non-speech batch

---

pyannote/audio/tasks/segmentation/segmentation.py
pyannote/audio/utils/loss.py
pyannote/audio/utils/powerset.py

feat: add `weigh_by_cardinality` option

---

CHANGELOG.md
notebook/augmentation.ipynb
pyannote/audio/core/io.py
pyannote/audio/core/model.py
pyannote/audio/interactive/common/utils.py
pyannote/audio/interactive/diff/recipe.py
pyannote/audio/interactive/pipeline/recipe.py
pyannote/audio/interactive/review/recipe.py
pyannote/audio/pipelines/utils/oracle.py
pyannote/audio/utils/preview.py
pyannote/audio/utils/protocol.py
tests/io_test.py
tutorials/intro.ipynb
tutorials/speaker_verification.ipynb

To keep the same behavior as before
* replace `Audio()` by `Audio(mono="downmix")`
* replace `Audio(mono=True)` by `Audio(mono="downmix")`
* replace `Audio(mono=False)` by become `Audio()`

BREAKING: update default behavior of Audio wrt to multi-channel

---

CHANGELOG.md
pyannote/audio/core/inference.py
pyannote/audio/core/pipeline.py
pyannote/audio/utils/reproducibility.py

fix(pipeline): fix reproducibility issue with Ampere CUDA device

---

pyannote/audio/core/inference.py
pyannote/audio/core/pipeline.py
pyannote/audio/pipelines/speaker_verification.py
pyannote/audio/utils/reproducibility.py

fix: pipeline/inference.to(device) supports only touch.device

---

CHANGELOG.md
pyannote/audio/pipelines/speaker_verification.py
requirements.txt

BREAKING: prepare for getting rid of ONNX runtime

---

pyannote/audio/models/blocks/pooling.py

"linear" interpolation is not yet supported by MPS, but "nearest" is.

fix(mps): fix support for MPS

---

CHANGELOG.md
pyannote/audio/models/embedding/__init__.py
pyannote/audio/models/embedding/wespeaker/LICENSE.WeSpeaker
pyannote/audio/models/embedding/wespeaker/__init__.py
pyannote/audio/models/embedding/wespeaker/convert.py
pyannote/audio/models/embedding/wespeaker/resnet.py
pyannote/audio/pipelines/speaker_verification.py
pyannote/audio/pipelines/utils/diarization.py

feat(model): add WeSpeaker embedding wrapper based on pytorch

---

CHANGELOG.md
pyannote/audio/models/blocks/sincnet.py
pyannote/audio/models/segmentation/PyanNet.py
pyannote/audio/models/segmentation/SSeRiouSS.py
pyannote/audio/models/segmentation/debug.py
pyannote/audio/utils/frame.py

cc @Bilal-Rahou this is somehow related to the discussion we had on Monday.

feat: add num_frames and receptive_field methods

---

CHANGELOG.md
pyannote/audio/torchmetrics/functional/audio/diarization_error_rate.py
tests/test_metrics.py

@FrenchKrab - will be useful for plots like today's 
@Bilal-Rahou - supersedes #1545

feat(metric): add `reduce` option to `diarization_error_rate` metric

---

CHANGELOG.md
pyannote/audio/core/io.py
pyannote/audio/pipelines/speaker_verification.py
pyannote/audio/tasks/segmentation/mixins.py
requirements.txt

improve(io): switch to torchaudio >= 2.2.0

---

CHANGELOG.md
pyannote/audio/core/task.py

cc @FrenchKrab can you please check it solves your issue #1709?
Disclaimer: I did not do any test :)

fix: fix #1709

---

CHANGELOG.md
pyannote/audio/pipelines/speaker_diarization.py
pyannote/audio/pipelines/speaker_verification.py
pyannote/audio/pipelines/speech_separation.py

Fix numpy.NAN which is numpy.nan

---

pyannote/audio/core/model.py
pyannote/audio/core/pipeline.py

fix: fix local pipeline loading (with models in subfolders)
